### ISSUE TITLE
Size of K

### ISSUE THREAD

**Issue by randomminer** [Dkpe/Kuberbitcore#2]
I know you are proud of the K in the wallet but not everyone runs max resolution and the bottom of the wallet is being clipped off. Could you make the K about .75 or .50 so the window size can be reduced. Thanks.

**Comment by Dkpe** [comment]
> I know you are proud of the K in the wallet but not everyone runs max resolution and the bottom of the wallet is being clipped off. Could you make the K about .75 or .50 so the window size can be reduced. Thanks.

Could you kindly indicate in a printscreen , I'm assuming it's the K in the main wallet page

**Comment by Dkpe** [comment]
128x128 px loaded - Will create a windows wallet soon closing
